name: Run Tests

on: [push]

jobs:
  test_v8_0_3_-_v8_1_0:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Checkout SDK
      uses: actions/checkout@v4
      with:
        repository: julusian/atemsdk
        token: ${{ secrets.ATEMSDK_TOKEN }}
        path: AtemSDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1.2

    - name: Build
      run: |
        regsvr32 $Env:GITHUB_WORKSPACE/AtemSDK/v8.1.0/BMDSwitcherAPI.dll /s
        regsvr32 $Env:GITHUB_WORKSPACE/AtemSDK/v8.1.0/BMDSwitcherAPI64.dll /s
        
        dotnet restore

        msbuild .\LibAtem.ComparisonTests.sln /property:Platform=v8.1 /property:Configuration=Release
        cp $Env:GITHUB_WORKSPACE/AtemSDK/v8.1.0/Interop.BMDSwitcherAPI.dll LibAtem.MockTests/bin/v8.1.1/Release/net8.0-windows/
    - name: Test
      run: |
        vstest.console.exe LibAtem.MockTests/bin/v8.1/Release/net8.0-windows/LibAtem.MockTests.dll
  test_v8_1_1_-_v9_5_0:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Checkout SDK
      uses: actions/checkout@v4
      with:
        repository: julusian/atemsdk
        token: ${{ secrets.ATEMSDK_TOKEN }}
        path: AtemSDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0
        
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1.2

    - name: Build
      run: |
        # regsvr32 $Env:GITHUB_WORKSPACE/AtemSDK/v9.5.0/BMDSwitcherAPI.dll /s
        regsvr32 $Env:GITHUB_WORKSPACE/AtemSDK/v9.5.0/BMDSwitcherAPI64.dll /s

        dotnet restore

        msbuild .\LibAtem.ComparisonTests.sln /property:Platform=v8.1.1 /property:Configuration=Release
        cp $Env:GITHUB_WORKSPACE/AtemSDK/v9.5.0/Interop.BMDSwitcherAPI.dll LibAtem.MockTests/bin/v8.1.1/Release/net8.0-windows/
    - name: Test
      run: |
        vstest.console.exe LibAtem.MockTests/bin/v8.1.1/Release/net8.0-windows/LibAtem.MockTests.dll
